### ISSUE TITLE
wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by FraLarghi** [fluent/fluent-plugin-mongo#112]
Hi!
With my configuration, I want to take from udp cef formatted logs, parsing with cef plugin and then put them in mongo. This is my fluentd conf file:

```
<source>
  @type udp
  port 5140
  bind 0.0.0.0
  tag logs.vendor
  source_hostname_key source_hostname
  <parse>
    @type cef
  </parse>
</source>

<match logs.**>
  @type mongo_replset
  nodes localhost:27017,localhost:27018,localhost:27019
  replica_set rset
  
  replace_dot_in_key_with _

  database logs
  collection ${tag}

  capped
  capped_size 100m

  <buffer>
    flush_interval 5s
  </buffer>
</match>
```

This is the error stacktrace:

```
2018-12-19 09:33:21 +0000 [info]: starting fluentd-1.3.1 pid=8 ruby="2.3.3"
2018-12-19 09:33:21 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/usr/local/bin/fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2018-12-19 09:33:21 +0000 [info]: gem 'fluent-plugin-mongo' version '1.2.0'
2018-12-19 09:33:21 +0000 [info]: gem 'fluent-plugin-parser_cef' version '1.0.0'
2018-12-19 09:33:21 +0000 [info]: gem 'fluentd' version '1.3.1'
2018-12-19 09:33:21 +0000 [info]: adding match pattern="logs.**" type="mongo_replset"
2018-12-19 09:33:21 +0000 [warn]: #0 Since v0.8, invalid record detection will be removed because mongo driver v2.x and API spec don't provide it. You may lose invalid records, so you should not send such records to mongo plugin
2018-12-19 09:33:21 +0000 [info]: adding source type="forward"
2018-12-19 09:33:21 +0000 [info]: adding source type="udp"
2018-12-19 09:33:22 +0000 [info]: #0 utc_offset: +00:00
2018-12-19 09:33:22 +0000 [warn]: #0 running without strict mode because of the following error
2018-12-19 09:33:22 +0000 [warn]: #0 No such file or directory @ rb_sysopen - /var/lib/gems/2.3.0/gems/fluent-plugin-parser_cef-1.0.0/lib/fluent/plugin/config/cef_version_0_keys.yaml
2018-12-19 09:33:22 +0000 [info]: #0 starting fluentd worker pid=32 ppid=8 worker=0
2018-12-19 09:33:22 +0000 [info]: #0 listening udp socket bind="0.0.0.0" port=5140
2018-12-19 09:33:22 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
2018-12-19 09:33:22 +0000 [info]: #0 fluentd worker is now running worker=0
2018-12-19 09:33:28 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 3, expected 2)"
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mongo-1.2.0/lib/fluent/plugin/out_mongo_replset.rb:39:in `operate'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mongo-1.2.0/lib/fluent/plugin/out_mongo.rb:177:in `write'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-mongo-1.2.0/lib/fluent/plugin/out_mongo_replset.rb:33:in `write'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.1/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.1/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.1/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2018-12-19 09:33:28 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.3.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-12-19 09:33:28 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3ff733a6d884/57d5cb4895907c351276c66296098a02.log
2018-12-19 09:33:33 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 3, expected 2)"
  2018-12-19 09:33:33 +0000 [warn]: #0 suppressed same stacktrace
```
This is an example log printed with stdout plugin (not with all the real fields):
```
2018-12-19 09:22:11.000000000 +0000 logs.vendor: {"cef_version":"0","cef_device_vendor":"vendor-x","cef_device_product":"VPN-1 & FireWall-1","cef_device_version":"version-x","cef_device_event_class_id":"Log","cef_name":"Log","cef_severity":"Unknown","act":"Bypass","cn1Label":"Email Recipients Number","cs1Label":"Email ID","cs4Label":"Email Control","cs4":"SMTP Policy Restrictions","cs5Label":"Email Session ID","deviceDirection":"0","msg":"Encrypted session","rt":"1545211330000","spt":"4001","dpt":"25"}
```

Fluentd is deployed with docker, fluent-plugin-mongo and fluent-plugin-parser_cef are installed as explained on docker hub instructions and seems to work fine separately.

Is something wrong or does mongo need some particular fields?

**Comment by cosmo0920** [comment]
I've found the root cause of this issue.
Could you try #113?

**Comment by FraLarghi** [comment]
Yes it's working with the pull request on #113 
Thank man!

**Comment by repeatedly** [comment]
Release v1.2.1 for the fix.
