### ISSUE TITLE
database needs to be set even if connection_string is set

### ISSUE THREAD

**Issue by tomohiro-n** [fluent/fluent-plugin-mongo#116]
### Gems
- fluentd (1.4.1)
- fluent-plugin-mongo (1.2.1)

### MongoDB
4.0.3

## What happened

I couldn't insert any data with a config like the following.

```
<match mongo.*>
  @type mongo
  
  connection_string mongodb://testUser:testPass@localhost:27017/testDb
  #database testDb
```

and it caused:

```
2019-03-29 16:48:17 +0900 [warn]: #0 fluent/log.rb:342:warn: got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `include?' for nil:NilClass"
  2019-03-29 16:48:17 +0900 [warn]: #0 plugin/output.rb:454:block (2 levels) in start: /Users/tomohiro/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/fluentd-1.4.1/lib/fluent/plugin/output.rb:733:in `extract_placeholders'
  2019-03-29 16:48:17 +0900 [warn]: #0 plugin/output.rb:454:block (2 levels) in start: /Users/tomohiro/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/fluent-plugin-mongo-1.2.1/lib/fluent/plugin/out_mongo.rb:176:in `write'
```

## My workaround and the potential cause

At a glance, after this commit https://github.com/fluent/fluent-plugin-mongo/commit/803821a8e50b2b10d4a684c7e5d697ead6214de6 , `database` needs to be set even if `connection_string` is there.
I added `database` property like the following and the issue is gone.

```
  connection_string mongodb://testUser:testPass@localhost:27017/testDb
  database testDb
```

I believe `database` is expected to be extracted from `connection_string` in this case.

**Comment by cosmo0920** [comment]
Sorry for inconvenience which is originated my patch bug.
Could you check #117?

**Comment by tomohiro-n** [comment]
@cosmo0920 Thanks for the quick fix! I put a comment on the PR.
