### ISSUE TITLE
Unable to output events to sharded cluster

### ISSUE THREAD

**Issue by mmussomele** [fluent/fluent-plugin-mongo#119]
I'm trying to set up fluentd to output events to a sharded mongo cluster. The mongo cluster has 3 nodes, and on each node there is 1 config server, 1 shard server and 1 mongos router. The shard servers are a replica set, and the config servers are a replica set. The fluentd logs are below:
```
2019-04-18 23:21:35 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    @id forward_input
    bind "0.0.0.0"
    port 24225
    <transport tls>
      cert_path /path/to/cert
      private_key_path /path/to/priv/key
      client_cert_auth true
      ca_path /path/to/ca
    </transport>
  </source>
  <match test.*>
    @type mongo
    collection "test"
    connection_string "mongodb://<username>@<mongosIP0>:27017,<mongosIP1>:27017,<mongosIP2>:27017/<database>?connect=sharded&readPreference=nearest&authMechanism=MONGODB-X509&authSource=%24external"
    ssl true
    ssl_cert /path/to/cert
    ssl_key /path/to/priv/key
    ssl_verify true
    ssl_ca_cert /path/to/ca
    buffer_chunk_limit 8m
    time_key time
    <buffer>
      @type "file"
      flush_mode immediate
      flush_at_shutdown true
      compress gzip
      overflow_action drop_oldest_chunk
    </buffer>
    <inject>
      time_key time
    </inject>
  </match>
</ROOT>
2019-04-18 23:21:35 +0000 [info]: starting fluentd-1.3.3 pid=28452 ruby="2.4.5"
2019-04-18 23:21:35 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "-c", "fluentd.conf", "--under-supervisor"]
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.0.1'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-kafka' version '0.8.3'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-mongo' version '1.2.2'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.7'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-04-18 23:21:35 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-04-18 23:21:35 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-04-18 23:21:35 +0000 [info]: adding match pattern="test.*" type="mongo"
2019-04-18 23:21:36 +0000 [warn]: #0 Since v0.8, invalid record detection will be removed because mongo driver v2.x and API spec don't provide it. You may lose invalid records, so you should not send such records to mongo plugin
2019-04-18 23:21:36 +0000 [info]: adding source type="forward"
2019-04-18 23:21:36 +0000 [warn]: #0 [forward_input] For security reason, setting private_key_passphrase is recommended when cert_path is specified
2019-04-18 23:21:36 +0000 [info]: #0 starting fluentd worker pid=28625 ppid=28452 worker=0
2019-04-18 23:21:36 +0000 [info]: #0 [forward_input] listening port port=24225 bind="0.0.0.0"
2019-04-18 23:21:36 +0000 [warn]: #0 [forward_input] For security reason, setting private_key_passphrase is recommended when cert_path is specified
2019-04-18 23:21:36 +0000 [info]: #0 fluentd worker is now running worker=0
2019-04-18 23:22:37 +0000 [warn]: #0 no patterns matched tag="fluent.info"
2019-04-18 23:22:37 +0000 [warn]: #0 no patterns matched tag="fluent.info"
2019-04-18 23:23:12 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-04-18 23:23:13 +0000 chunk="586d6475efa77f657bb5419f800fc75f" error_class=Mongo::Error::NoServerAvailable error="No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47219167572380 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015"
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/mongo-2.6.4/lib/mongo/server_selector/selectable.rb:115:in `select_server'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/mongo-2.6.4/lib/mongo/cluster.rb:263:in `next_primary'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mongo-1.2.2/lib/fluent/plugin/out_mongo.rb:218:in `list_collections_enabled?'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mongo-1.2.2/lib/fluent/plugin/out_mongo.rb:222:in `collection_exists?'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mongo-1.2.2/lib/fluent/plugin/out_mongo.rb:236:in `get_collection'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mongo-1.2.2/lib/fluent/plugin/out_mongo.rb:261:in `operate'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mongo-1.2.2/lib/fluent/plugin/out_mongo.rb:178:in `write'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-04-18 23:23:12 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-04-18 23:23:43 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-04-18 23:23:44 +0000 chunk="586d6475efa77f657bb5419f800fc75f" error_class=Mongo::Error::NoServerAvailable error="No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47219167572380 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015"
more retries...
```
Why is the plugin trying to find a primary server if the specified addresses are mongos instances? I've tried specifying the connect method to sharding to override this but nothing seems to work. Would very much appreciate any help.

FWIW, I have verified that the mongo cluster is fine. It works and I can talk to it and manipulate it manually using `mongo` shell.

Also note that some fields have been omitted from the configuration for privacy reasons (replaced by `<foo>`).

Edit: I don't know ruby, but it seems like the plugin is attempting to [get a primary member of the mongo deployment](https://github.com/fluent/fluent-plugin-mongo/blob/master/lib/fluent/plugin/out_mongo.rb#L218) regardless of the type of mongo instance it is connected to.

**Comment by mmussomele** [comment]
Update: After digging through the plugin and mongo ruby driver code, it seems that the ssl options given in the plugin are not respected if using a connection string, and you must specify tls configuration as connection string options instead. Because of this, the plugin was failing to connect to the mongos instances (which require SSL), and the servers list was empty.

Perhaps it should be documented that none of the client options are used if connection_string is supplied?

**Comment by mmussomele** [comment]
Currently testing a patch to support specifying auth mechanism/source. Will submit a PR for consideration if it works.
