### ISSUE TITLE
Unable to use ${record[key]} to set collection dynamically

### ISSUE THREAD

**Issue by davidebersani** [fluent/fluent-plugin-mongo#141]
Hi everyone,
I have an application that write something in json in the log.
I have managed to extract field from the json with a simple parser filter. One of the fields is "metric".
I want to use this field to set the collection name, so I write this:
```
<match event>
    # plugin type
    @type mongo

    database metrics
    collection ${record["metric"]}

    .... other parameters ... 
  </match>
```

but it doesn't work and the fluentd's log print:

```
2020-06-14 09:53:31 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-06-14 09:53:32 +0000 chunk="5a80847cddb08f474d372ba078fb3624" error_class=Mongo::Error::OperationFailure error="invalid collection name (73)"
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/operation/result.rb:267:in `raise_operation_failure'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/operation/result.rb:263:in `validate!'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/operation/create/op_msg.rb:32:in `execute'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/operation/create.rb:41:in `execute'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/collection.rb:197:in `block in create'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/cluster.rb:532:in `with_session'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/client.rb:550:in `with_session'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/mongo-2.6.4/lib/mongo/collection.rb:191:in `create'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-mongo-1.4.0/lib/fluent/plugin/out_mongo.rb:276:in `get_collection'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-mongo-1.4.0/lib/fluent/plugin/out_mongo.rb:299:in `operate'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-mongo-1.4.0/lib/fluent/plugin/out_mongo.rb:187:in `write'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1128:in `try_flush'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:1434:in `flush_thread_run'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.6.3/lib/fluent/plugin/output.rb:457:in `block (2 levels) in start'
  2020-06-14 09:53:31 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.6.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create' 
```

I tried to use `${tag}` instead of `${record["metric"]}` and it works. So why this solution doesn't work?

Thank you.

**Comment by cosmo0920** [comment]
```aconf
<match event>
    # plugin type
    @type mongo

    database metrics
    collection ${metric}

    .... other parameters ... 
    <buffer tag, metric>
       # some buffer parameters.
    </buffer
</match>
```

can handle values of `metric` records.

**Comment by repeatedly** [comment]
cosmo0920 shows the proper configuration. Closed.
