### ISSUE TITLE
how to support mutlprocess

### ISSUE THREAD

**Issue by pierce300** [fluent/fluent-plugin-mongo#55]
HI
  i try to modified code for  support multiprocess for mongo plugin, below is code:
    def start
      get_or_create_collection(@collection) unless @tag_mapped
      @buffer.buffer_chunk_limit = available_buffer_chunk_limit
      detach_multi_process do
        super
      end
    end
but not work,below is error infomatin
2015-07-09 12:45:45 +0800 [warn]: failed to emit error="undefined method `next' for nil:NilClass" pid=11030
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:184:in `block in emit'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:179:in `emit'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:251:in `emit'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mongo-0.7.8/lib/fluent/plugin/out_mongo.rb:116:in `emit'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:152:in `block in output_forward_main'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:205:in `call'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:205:in `block in read_event_stream'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:202:in `each'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:202:in `read_event_stream'
  2015-07-09 12:45:45 +0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/process.rb:147:in `output_forward_main'

**Comment by repeatedly** [comment]
AKAIK, `detach_multi_process` is for input plugin so it can't be used with Output plugins.

**Comment by repeatedly** [comment]
You can use `num_threads` for improving insert performance and
`multiprocess` plugin is for improving entire performance.
