### ISSUE TITLE
undefined method `time_key' for nil:NilClass

### ISSUE THREAD

**Issue by porkbeans** [fluent/fluent-plugin-mongo#92]
I cannot insert into our mongo with 1.0.0.rc2.
fluentd v0.14.21 printed followings.
```
failed to flush the buffer. retry_time=0 next_retry_seconds=2017-09-20 13:07:21 +0000 chunk="5599e28e651d49684934c52d2a6eec30" error_class=NoMethodError error="undefined method `time_key' for nil:NilClass"
/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-mongo-1.0.0.rc2/lib/fluent/plugin/out_mongo.rb:194:in `collect_records'
/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-mongo-1.0.0.rc2/lib/fluent/plugin/out_mongo.rb:176:in `write'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:1061:in `try_flush'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:1286:in `flush_thread_run'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:438:in `block (2 levels) in start'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Am i doing something wrong in my setting?
```
<match app_log>
    @type mongo
    connection_string "mongodb://#{ENV['FLUENT_MONGO_NODES']}/app"
    collection app_log

    capped
    capped_size 1024m

    <buffer>
      @type file
      path "#{ENV['FLUENT_LOG_DIR']}/buffer/mongo-app_log.*"
      flush_interval 10s
    </buffer>
  </match>
```

P.S.
Looking at out_mongo.rb:194, `@inject_config` may be for only testing but it's not checked if exists.

**Comment by repeatedly** [comment]
It seems the bug of compat handling.
Patch is here: https://github.com/fluent/fluent-plugin-mongo/pull/93

**Comment by porkbeans** [comment]
@repeatedly It works! Thank you so much!

**Comment by navaati** [comment]
Hi. I'm running into this bug, will you make a new RC release soon ? What do you suggest to do otherwise ?

Cheers.

**Comment by repeatedly** [comment]
v1.0.0.rc3 released

**Comment by navaati** [comment]
Oh great, thanks !
